name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for contributing to Scalant. We love you and your Issue ❤️🎉 . Your issues, really help us with our project... Waiting for you to contribute again to Scalantcommunity
      ."
        pr-message: "Thank you for contributing to scalant. We love you and your PR ❤️🎉 . Waiting for you to contribute again to scalant"
